# Generated by Django 3.2.25 on 2024-12-15 12:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0003_recent'),
    ]

    operations = [
        migrations.CreateModel(
            name='biggestsales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.product')),
            ],
        ),
    ]
