# Generated by Django 3.2.25 on 2024-12-16 06:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_biggestsales'),
    ]

    operations = [
        migrations.CreateModel(
            name='mostview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewcount', models.IntegerField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Application.product')),
            ],
        ),
    ]
