# Generated by Django 3.2.25 on 2024-12-16 07:07

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0006_alter_mostview_viewcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='recent',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
