# Generated by Django 3.2.25 on 2024-12-29 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0007_recent_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='originalprice',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, max_digits=1000000),
            preserve_default=False,
        ),
    ]
